name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

# registration date or jamboree date is called UPCOMING_DATE (below)
# jekyll date format: YYYY-MM-DD HH:MM:SS +/-TTTT

# team registration
# upcoming_date: "Apr 30 2014 23:59:00"

# jamboree registration
upcoming_date: "Sep 12 2014 23:59:00"

# important dates
#team_registration_deadline: 2014-04-30 23:59:00 -0400
team_registration_deadline: "Apr 30 2014 23:59:00"
judging_criteria_posted: "May 1 2014 23:59:00"
visa_letter_requests:  "Jul 1 2014 23:59:00"
jamboree_registration_deadline: "Sep 12 2014 23:59:00"
project_abstract_deadline: "Sep 12 2014 23:59:00"
# wiki video deadline supposed to be in Pacific time zone
wiki_video_deadline: "Oct 25 2014 23:59:00"
hotel_checkin_time: "Oct 31 2014 15:00:00"
jamboree_start_time: "Nov 1 2014 09:00:00"
hotel_checkout_time: "Nov 2 2014 11:00:00"
