name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

# The month in javascript's Date constructor is 0-indexed,
# so for clarity we use the numeric month but explicity subtract 1 inline
# format is for javascript Date function ( year, month-1, day, hour, minute )
registration_date: 2014, 4-1, 30, 23, 59

# not used yet, but could be used same way as registration:
# jamboree_date: 2014, 11-1, 1, 9, 00