name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap

# registration date or jamboree date is called UPCOMING_DATE (below)
# jekyll date format: YYYY-MM-DD HH:MM:SS +/-TTTT

# wiki_video deadline
# upcoming_date: "Oct 27 2017 23:59:00 -1000"
upcoming_date: "Oct 20 2018 11:59:00"

# important dates
team_registration_opens: "Feb 14 2018 14:00:00"
team_registration_deadline: "Apr 30 2018 23:59:00"
judging_criteria_posted: "May 1 2018 23:59:00"
jamboree_registration_start: "May 1 2018 00:00:00"
visa_letter_requests: "Jul 1 2018 00:00:00"
jamboree_registration_deadline: "Sep 26 2018 23:59:00"
project_abstract_deadline: "Oct 1 2018 23:59:00"
wiki_video_deadline: "Oct 20 2018 11:59:00"
hotel_checkin_time: "Oct 26 2018 15:00:00"
jamboree_start_time: "Oct 27 2018 08:00:00"
hotel_checkout_time: "Oct 28 2018 11:00:00"
jamboree_end_time: "Oct 28 2018 17:00:00"

team_registration_fee: 265
individual_registration_fee: 195
