name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: redcarpet
pygments: true
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->
