name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap

# registration date or jamboree date is called UPCOMING_DATE (below)
# jekyll date format: YYYY-MM-DD HH:MM:SS +/-TTTT

# wiki_video deadline
# upcoming_date: "Oct 27 2017 23:59:00 -1000"
upcoming_date: "Mar 1 2020 14:00:00"

# important dates
team_registration_opens: "Mar 1 2020 14:00:00"
team_registration_deadline: "Jul 30 2020 23:59:00"
judging_criteria_posted: "May 1 2020 23:59:00"
jamboree_registration_start: "May 1 2020 00:00:00"
visa_letter_requests: "Jul 1 2020 00:00:00"
jamboree_registration_deadline: "Feb 1 2020 23:59:00"
project_abstract_deadline: "Feb 1 2020 23:59:00"
wiki_video_deadline: "Mar 5 2020 11:59:00"
hotel_checkin_time: "Mar 12 2020 15:00:00"
jamboree_start_time: "Mar 13 2020 08:00:00"
hotel_checkout_time: "Mar 14 2020 11:00:00"
jamboree_end_time: "Mar 14 2020 17:00:00"

team_registration_fee: 300
individual_registration_fee: 225
