name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap

# registration date or jamboree date is called UPCOMING_DATE (below)
# jekyll date format: YYYY-MM-DD HH:MM:SS +/-TTTT

# team registration deadline
# upcoming_date: "Oct 27 2017 23:59:00 -1000"
upcoming_date: "May 31 2023 23:59:00 +09:00" # JST / UTC+0900

# important dates
team_registration_opens: "Apr 29 2023 12:00:00 +09:00"
team_registration_deadline: "May 31 2023 23:59:00 +09:00"
#judging_criteria_posted: "Jun 30 2020 23:59:00"
jamboree_registration_start: "Aug 15 2023 00:00:00 +09:00"
visa_letter_requests: "Sep 1 2023 00:00:00 +09:00"
jamboree_registration_deadline: "Sep 15 2023 23:59:00 +09:00"
project_abstract_deadline: "Sep 15 2023 23:59:00 +09:00"
wiki_video_deadline: "Oct 28 2023 11:59:00 +09:00"
#hotel_checkin_time: "Mar 12 2021 15:00:00"
jamboree_start_time: "Nov 4 2023 09:00:00 +09:00"
#hotel_checkout_time: "Mar 14 2021 11:00:00"
jamboree_end_time: "Nov 5 2023 14:00:00 +09:00"

team_registration_fee: 30000 #JPY
individual_registration_fee: "TBD"
