name: BIOMOD
description: International Bio-molecular Design Competition
url: http://biomod.net
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "blog/page:num/index.html"
excerpt_separator: <!--more-->

gems:
  - jekyll-redirect-from
  - jekyll-paginate

# registration date or jamboree date is called UPCOMING_DATE (below)
# jekyll date format: YYYY-MM-DD HH:MM:SS +/-TTTT

# wiki_video deadline
upcoming_date: "Apr 30 2017 23:59:00"

# important dates
team_registration_opens: "Feb 15 2017 14:00:00"
team_registration_deadline: "Apr 30 2017 23:59:00"
judging_criteria_posted: "May 1 2017 23:59:00"
jamboree_registration_start: "Jul 25 2017 00:00:00"
jamboree_registration_deadline: "Oct 2 2017 23:59:00"
project_abstract_deadline: "Oct 2 2017 23:59:00"
# wiki video deadline supposed to be in Pacific time zone
wiki_video_deadline: "Oct 27 2017 11:59:00"
hotel_checkin_time: "Nov 3 2017 15:00:00"
jamboree_start_time: "Nov 4 2017 08:00:00"
hotel_checkout_time: "Nov 5 2017 11:00:00"
jamboree_end_time: "Nov 5 2017 17:00:00"
visa_letter_requests: "Jul 1 2017 00:00:00"

team_registration_fee: 255
individual_registration_fee: 185
